language: java

jdk:
  - oraclejdk8

env:
  global:
    - HEROKU_API_KEY="6dbf52d0-96e7-4ae2-a964-c1a31cdaffa8"

cache:
  directories:
    - "$HOME/.m2/repository"

notifications:
  email: true

install: true

before_script:
  - echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc

script:
  - mvn clean install -B -V
  - mvn sonar:sonar -Dsonar.organization=intellecteu -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_API_KEY

deploy:
  provider: script
  script:
    - mvn -f initializr-service/pom.xml heroku:deploy -DskipTests
  app: catalyst-bootstrap
  on: master
