language: java
jdk:
  - oraclejdk8
notifications:
  email: false
# git strips the wrapper jar file so we have to force its download during the build.
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -Dmaven.javadoc.skip=true -B -V
# - mvn clean install -B -V
# - mvn -f initializr-service/pom.xml heroku:deploy
deploy:
  provider:     heroku
  app:          catalyst-bootstrap
  on:           master
  skip_cleanup: true
  api_key:
    secure:     "6dbf52d0-96e7-4ae2-a964-c1a31cdaffa8"
