language: java

sudo: false
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

env:
  global:
    - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

notifications:
  email: true

install: true

before_script:
  - echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc

script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn clean install deploy -B -V -Pfull -Dusername=${ARTIFACTORY_USERNAME} -Dpassword=${ARTIFACTORY_PASSWORD}
# Use these for maven wrapper - git strips the wrapper jar file so we have to force its download during the build.
#  - mvn -N io.takari:maven:wrapper
#  - ./mvnw install -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

before_deploy:
  - mvn sonar:sonar -Dsonar.organization=intellecteu -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_API_KEY -Pfull

deploy:
  provider: script
  script:
    - mvn -f catalyst-service/pom.xml heroku:deploy -DskipTests
  app: catalyst-bootstrap
  on:
    branch: master

