language: java
jdk:
  - oraclejdk8
env:
  global:
    - HEROKU_API_KEY="6dbf52d0-96e7-4ae2-a964-c1a31cdaffa8"
#    - MAVEN-OPTS:"-B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
notifications:
  email: false

before_script:
  - echo "MAVEN_OPTS='-B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc

script:
#  - mvn -N io.takari:maven:wrapper
#  - ./mvnw install -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
#  - mvn -f initializr-service/pom.xml heroku:deploy
  - mvn install
deploy:
#  provider:     heroku
#  app:          catalyst-bootstrap
#  on:           master
#  api_key:
#    secure:     "6dbf52d0-96e7-4ae2-a964-c1a31cdaffa8"
  provider:     script
  script:       "mvn heroku:deploy"
  skip_cleanup: true
  app:          catalyst-bootstrap
  on:           master
