spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3390/CorporateUsers
    username: ''
    password: ''
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      maximum-pool-size: 50
      pool-name: appConnectionPool

catalyst:
  sql:
    onConsume: ''
    query: ''
    enabled: false
